version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      # DATABASE_URL: postgres://user:pass@postgres:5432/db
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DATABASE: db
      POSTGRES_PORT: 5432
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: sh -c './wait-for postgres:5432 -- npm run test'
    volumes:
      - //Users/andrewbrown/src/github.com/quantafinance/quanta-platform/tests:/home/node/tests
      - //Users/andrewbrown/src/github.com/quantafinance/quanta-platform/pages/api:/home/node/pages/api
      - //Users/andrewbrown/src/github.com/quantafinance/quanta-platform/next.config.js:/home/node/next.config.js
      - //Users/andrewbrown/src/github.com/quantafinance/quanta-platform/package.json:/home/node/package.json

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    volumes:
      - //Users/andrewbrown/src/github.com/quantafinance/quanta-platform/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
